# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name : checkout
      uses: actions/checkout@v3
    
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12.16
        cache: 'npm'
        
    - name : Install    
      run: npm ci
    
    - name : build
      run: npm run build --if-present
      
    - name : firebase-deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WEB_SPACEFARM_562E6 }}'
          channelId: live
          projectId: gitactions-6236a
        env:
          CI: true
          FIREBASE_CLI_PREVIEWS: hostingchannels
